= Modelo de livro em AsciiDoc

Modelo criado em AsciiDoc para produção de conteúdo em forma de livro.

Foi criado um tema customizado para o livro que utiliza as fontes Bitter, Roboto e Fira Code Nerd Font para o texto, cabeçalhos e código, respectivamente. Também adiciona uma imagem como capa frontal e outra como capa traseira, além de trazer uma organização inicial das seções (ainda existem pontos a serem melhorados). 

Contribuições serão ben vindas

== Requisitos

Para gerar o arquivo PDF do livro é utilizado o contêiner `docker-asciidoctor` no *Podman Desktop* (pode ser utilizado o Docker também).

Para instalar o *Podman Destop*, basta acessar este https://podman-desktop.io/docs/installation[link] e seguir as instruções referentes ao seu sistema operacional

Para iniciar um contêiner no Podman Desktop, basta executar o seguinte comando:

[,bash]
----
podman run -it -v ./:/documents/ docker.io/asciidoctor/docker-asciidoctor
----

== Gerando o PDF do livro

Após iniciar o conmtêiner com o *Podman Desktop* podemos gerar o arquivo PDF do livro com o seguinte comando:

[,bash]
----
make
----

Será gerado uma pasta `output` com um arquivo chamado *book.pdf*.